services:
  slideshow-my-life:
    image: node:lts-alpine3.17
    command: sh -c "npm install && npm run dev-host"
    ports:
      - 127.0.0.1:5173:5173
    working_dir: /app
    volumes:
      - ./:/app